# Generated by Django 5.1.5 on 2025-01-22 17:12

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Post Title")),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "title_tag",
                    models.CharField(max_length=255, verbose_name="Post Title Tag"),
                ),
                (
                    "body",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Post Content"
                    ),
                ),
                ("post_date", models.DateField(auto_now_add=True)),
                ("category", models.CharField(default="coding", max_length=255)),
                ("snippet", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shares",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="target_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/profile/"
                    ),
                ),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "twitter_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "instagram_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pinterest_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
