# Generated by Django 4.2.17 on 2025-01-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, default="default-slug", unique=True),
        ),
    ]
