# Generated by Django 5.1.5 on 2025-01-25 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="shares",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("body", models.TextField(max_length=200)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="myblog.post",
                    ),
                ),
            ],
        ),
    ]
