# Generated by Django 5.1.4 on 2025-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Post Title Tag"
            ),
            preserve_default=False,
        ),
    ]
