# Generated by Django 5.1.4 on 2025-01-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(
                default="My Freakin' Awesome Blog",
                max_length=255,
                verbose_name="Post Title Tag",
            ),
        ),
    ]
