# Generated by Django 4.2.17 on 2025-01-19 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myblog", "0004_post_dislikes_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shares",
            field=models.ManyToManyField(
                blank=True, related_name="shared_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
