# Generated by Django 5.1.4 on 2025-01-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0004_alter_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(max_length=255, verbose_name="Post Title Tag"),
        ),
    ]
