# Generated by Django 4.2.17 on 2025-01-19 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myblog", "0005_post_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="target_users",
            field=models.ManyToManyField(
                blank=True, related_name="target_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
