# Generated by Django 4.2.17 on 2025-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0008_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click Link Above To Read Blog Post....", max_length=255
            ),
        ),
    ]
