# Generated by Django 4.2.17 on 2025-01-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0010_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
