# Generated by Django 5.1.5 on 2025-01-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
