# Generated by Django 4.2.17 on 2025-01-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="profile",
            name="password",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
