# Generated by Django 4.2.17 on 2025-01-15 08:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_remove_profile_avatar_profile_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.CharField(
                max_length=128, verbose_name=django.contrib.auth.models.User
            ),
        ),
    ]
